import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {cn} from "@/lib/utils";

import "./globals.css";
import {QueryProvider} from "@/components/query-provider";
import {Toaster} from "@/components/ui/sonner";
import { NuqsAdapter } from 'nuqs/adapters/next/app';

const inter = Inter({subsets: ["latin"]});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
        <body
            className={cn(inter.className, "antialiased h-full")}
        >
        <QueryProvider>
            <NuqsAdapter>
                <Toaster/>
                <main className="h-full">
                  {children}
                </main>
            </NuqsAdapter>
        </QueryProvider>
        </body>
        </html>
    );

}
